import numpy
array1=numpy.array([1,2,3,4,5,6],int)
print("the integer array is:\n",array1)
array2=numpy.array(['a','b','c','d','f'])
print("the character array is:\n",array2)
array3=numpy.array(['JK','MH','UP','TN'],dtpe=str)
print("the string array is:\n",array3)
array4=numpy.array([4.5,6.2,7.856,1.235],dtype=float)
print("the float array is:\n",array4)
array5=array1.view()
print("using view to create a new array is:\n",array5)
array6=array3.copy()
print("using copy to create a new array is:\n",array6)