import numpy as np
array7=np.arange(5)
print("the integer array using arranged() function is:\n",array7)
array8=np.arange(4,9,dtype=float)
print("the float array using arranged() function is:\n",array8)
array9=np.linspace(2,14,7)
print("the integer array using linspace() function is:\n")
array10=np.linspace(1.,4.,5)
print("the float array using linspace() function is:\n",array10)
array11=np.zeros((2))
print("arrays using zeroes:\n",array11)
array12=np.ones((3))
print("arrays using ones:\n",array12)